// src/pages/Destinations.jsx
import React, { useState } from "react";
import { MapContainer, TileLayer, Marker, Popup } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import "../styles/Destinations.css";

const destinations = [
  {
    id: 1,
    name: "Hampi",
    image: "/images/hampi.jpg",
    description: "Hampi is a UNESCO World Heritage Site in Karnataka, India, known for its ruins of the Vijayanagara Empire.",
    lat: 15.335,
    lng: 76.462,
  },
  {
    id: 2,
    name: "Santorini",
    image: "/images/santorini.jpg",
    description: "Famous for whitewashed buildings, blue domes, and breathtaking sunsets in Greece.",
    lat: 36.3932,
    lng: 25.4615,
  },
  {
    id: 3,
    name: "Paris",
    image: "/images/paris.jpg",
    description: "Paris is the capital of France, famous for the Eiffel Tower, art, and fashion.",
    lat: 48.8566,
    lng: 2.3522,
  },
  {
    id: 4,
    name: "Tokyo",
    image: "/images/download.jpeg",
    description: "Tokyo, the capital of Japan, is known for its modern architecture, shopping, and cuisine.",
    lat: 35.6895,
    lng: 139.6917,
  },
  {
    id: 5,
    name: "New York",
    image: "/images/newyork.jpg",
    description: "New York City is known for its iconic skyline, Times Square, and the Statue of Liberty.",
    lat: 40.7128,
    lng: -74.006,
  },
  {
    id: 6,
    name: "Dubai",
    image: "/images/dubai.jpg",
    description: "Dubai is known for luxury shopping, ultramodern architecture, and the Burj Khalifa.",
    lat: 25.276987,
    lng: 55.296249,
  },
  {
    id: 7,
    name: "Bali",
    image: "/images/bali.jpg",
    description: "Bali is an Indonesian island famous for beaches, coral reefs, and forested volcanic mountains.",
    lat: -8.3405,
    lng: 115.092,
  },
  {
    id: 8,
    name: "London",
    image: "/images/london.jpg",
    description: "London is the capital of the UK, known for Big Ben, the London Eye, and royal heritage.",
    lat: 51.5074,
    lng: -0.1278,
  },
  {
    id: 9,
    name: "Rome",
    image: "/images/rome.jpg",
    description: "Rome is the capital of Italy, famous for ancient architecture like the Colosseum and Vatican City.",
    lat: 41.9028,
    lng: 12.4964,
  },
  {
    id: 10,
    name: "Sydney",
    image: "/images/sydney.jpg",
    description: "Sydney, Australia is known for the Sydney Opera House and beautiful harbor beaches.",
    lat: -33.8688,
    lng: 151.2093,
  },
  {
    id: 11,
    name: "Bangkok",
    image: "/images/bangkok.jpg",
    description: "Bangkok, Thailand’s capital, is known for ornate shrines and vibrant street life.",
    lat: 13.7563,
    lng: 100.5018,
  },
  {
    id: 12,
    name: "Barcelona",
    image: "/images/barcelona.jpg",
    description: "Barcelona is famous for art, architecture, and the Sagrada Familia.",
    lat: 41.3851,
    lng: 2.1734,
  },
  {
    id: 13,
    name: "Istanbul",
    image: "/images/istanbul.jpg",
    description: "Istanbul connects Europe and Asia and is known for historic mosques and the Grand Bazaar.",
    lat: 41.0082,
    lng: 28.9784,
  },
  {
    id: 14,
    name: "Cape Town",
    image: "/images/capetown.jpg",
    description: "Cape Town is a coastal city in South Africa with Table Mountain and stunning beaches.",
    lat: -33.9249,
    lng: 18.4241,
  },
  {
    id: 15,
    name: "Cairo",
    image: "/images/cairo.jpg",
    description: "Cairo is Egypt's capital and is famous for ancient pyramids and the Sphinx.",
    lat: 30.0444,
    lng: 31.2357,
  },
  {
    id: 16,
    name: "Rio de Janeiro",
    image: "/images/rio.jpg",
    description: "Rio is known for Christ the Redeemer, Copacabana, and Carnival.",
    lat: -22.9068,
    lng: -43.1729,
  },
  {
    id: 17,
    name: "Singapore",
    image: "/images/singapore.jpg",
    description: "Singapore is a global financial hub with modern cityscapes and green spaces.",
    lat: 1.3521,
    lng: 103.8198,
  },
  {
    id: 18,
    name: "Los Angeles",
    image: "/images/la.jpg",
    description: "Los Angeles is the entertainment capital of the world, home to Hollywood.",
    lat: 34.0522,
    lng: -118.2437,
  },
  {
    id: 19,
    name: "Amsterdam",
    image: "/images/amsterdam.jpg",
    description: "Amsterdam is famous for canals, museums, and historic houses.",
    lat: 52.3676,
    lng: 4.9041,
  },
  {
    id: 20,
    name: "Venice",
    image: "/images/venice.jpg",
    description: "Venice is built on water with beautiful canals and Renaissance architecture.",
    lat: 45.4408,
    lng: 12.3155,
  },
  {
    id: 21,
    name: "Maldives",
    image: "/images/maldives.jpg",
    description: "Tropical paradise with luxury overwater villas.",
    lat: 3.2028,
    lng: 73.2207,
  },
  {
    id:22,
    name: "Mount Everest",
    image: "/images/everest.jpg",
    description: "World's tallest mountain in the Himalayas.",
    lat: 27.9881,
    lng: 86.925,
  },
  {
    id: 23,
    name: "Rio de Janeiro",
    image: "/images/rio.jpg",
    description: "Brazil's vibrant city with beaches and Christ the Redeemer.",
    lat: -22.9068,
    lng: -43.1729,
  },
  {
    id: 24,
    name: "Swiss Alps",
    image: "/images/swiss-alps.jpg",
    description: "Famous for skiing and snow-capped peaks.",
    lat: 46.8182,
    lng: 8.2275,
  },
  {
    id: 25,
    name: "Phuket",
    image: "/images/phuket.jpg",
    description: "Thailand's beach destination with vibrant nightlife.",
    lat: 7.8804,
    lng: 98.3923,
  },
  {
    id: 26,
    name: "Banff",
    image: "/images/banff.jpg",
    description: "Canadian national park with lakes and mountains.",
    lat: 51.1784,
    lng: -115.5708,
  },
  {
    id: 27,
    name: "Great Barrier Reef",
    image: "/images/great-barrier-reef.jpg",
    description: "World’s largest coral reef system in Australia.",
    lat: -18.2871,
    lng: 147.6992,
  },
  {
    id: 28,
    name: "Machu Picchu",
    image: "/images/machu-picchu.jpg",
    description: "Ancient Incan city high in Peru’s Andes.",
    lat: -13.1631,
    lng: -72.545,
  },
  {
    id: 29,
    name: "Amalfi Coast",
    image: "/images/amalfi.jpg",
    description: "Italian coast with colorful towns and cliffs.",
    lat: 40.6333,
    lng: 14.6029,
  },
  {
    id: 30,
    name: "Taj Mahal",
    image: "/images/tajmahal.jpg",
    description: "Iconic white marble mausoleum in Agra, a UNESCO World Heritage Site.",
    lat: 27.1751,
    lng: 78.0421,
  },
  {
    id: 31,
    name: "Jaipur",
    image: "/images/jaipur.jpg",
    description: "The Pink City, known for Hawa Mahal and Amer Fort.",
    lat: 26.9124,
    lng: 75.7873,
  },
  {
    id: 32,
    name: "Varanasi",
    image: "/images/varanasi.jpg",
    description: "One of the world's oldest cities, famous for the Ganga ghats.",
    lat: 25.3176,
    lng: 82.9739,
  },
  {
    id: 33,
    name: "Kerala Backwaters",
    image: "/images/kerala.jpg",
    description: "Lush backwaters and houseboat cruises in Alleppey and Kumarakom.",
    lat: 9.4981,
    lng: 76.3388,
  },
  {
    id: 34,
    name: "Goa",
    image: "/images/goa.jpg",
    description: "Popular beach destination with vibrant nightlife.",
    lat: 15.2993,
    lng: 74.124,
  },
  {
    id: 35,
    name: "Ladakh",
    image: "/images/ladakh.jpg",
    description: "Mountain desert known for monasteries and Pangong Lake.",
    lat: 34.1526,
    lng: 77.577,
  },
  {
    id: 36,
    name: "Mysore",
    image: "/images/mysore.jpg",
    description: "Known for the grand Mysore Palace and Dussehra festival.",
    lat: 12.2958,
    lng: 76.6394,
  },
  {
    id: 37,
    name: "Kolkata",
    image: "/images/kolkata.jpg",
    description: "Cultural capital of India, home to Victoria Memorial and Howrah Bridge.",
    lat: 22.5726,
    lng: 88.3639,
  },
  {
    id: 38,
    name: "Amritsar",
    image: "/images/amritsar.jpg",
    description: "Famous for the Golden Temple and Wagah Border ceremony.",
    lat: 31.634,
    lng: 74.8723,
  },
  {
    id: 39,
    name: "Udaipur",
    image: "/images/udaipur.jpg",
    description: "City of Lakes, known for City Palace and boat rides.",
    lat: 24.5854,
    lng: 73.7125,
  },
  {
    id: 40,
    name: "Rishikesh",
    image: "/images/rishikesh.jpg",
    description: "Yoga capital of the world and gateway to the Himalayas.",
    lat: 30.0869,
    lng: 78.2676,
  },
  {
    id: 41,
    name: "Darjeeling",
    image: "/images/darjeeling.jpg",
    description: "Tea plantations and the Himalayan toy train experience.",
    lat: 27.036,
    lng: 88.2627,
  },
  {
    id: 42,
    name: "Shimla",
    image: "/images/shimla.jpg",
    description: "Queen of Hills with colonial charm and scenic views.",
    lat: 31.1048,
    lng: 77.1734,
  },
  {
  id: 43,
  name: "Bengaluru",
  image: "/images/bengaluru.jpg",
  description: "India's Silicon Valley, known for its tech hubs, gardens, and pleasant climate.",
  lat: 12.9716,
  lng: 77.5946,
},
  {
    id: 44,
    name: "Ooty",
    image: "/images/ooty.jpg",
    description: "Hill station known for botanical gardens and toy train.",
    lat: 11.4064,
    lng: 76.6932,
  },
  {
    id: 45,
    name: "Mumbai",
    image: "/images/mumbai.jpg",
    description: "Financial capital of India, home to Bollywood and Gateway of India.",
    lat: 19.076,
    lng: 72.8777,
  },
  {
    id: 46,
    name: "Delhi",
    image: "/images/delhi.jpg",
    description: "Capital of India with historical sites like Red Fort and Qutub Minar.",
    lat: 28.6139,
    lng: 77.209,
  },
  {
    id: 47,
    name: "Meghalaya",
    image: "/images/meghalaya.jpg",
    description: "Lush green hills and living root bridges of Cherrapunji.",
    lat: 25.467,
    lng: 91.3662,
  },
  {
    id: 48,
    name: "Ranthambore",
    image: "/images/ranthambore.jpg",
    description: "Wildlife safari destination with Bengal tigers.",
    lat: 26.0173,
    lng: 76.5026,
  },
  {
    id: 49,
    name: "Andaman Islands",
    image: "/images/andaman.jpg",
    description: "Tropical paradise with clear waters and coral reefs.",
    lat: 11.7401,
    lng: 92.6586,
  },
  {
  id: 50,
  name: "Kyoto",
  image: "/images/kyoto.jpg",
  description: "Historic city in Japan known for its classical temples and geisha culture.",
  lat: 35.0116,
  lng: 135.7681,
},
{
  id: 51,
  name: "Seoul",
  image: "/images/seoul.jpg",
  description: "The capital of South Korea, a vibrant blend of traditional and modern culture.",
  lat: 37.5665,
  lng: 126.978,
},
{
  id: 52,
  name: "Petra",
  image: "/images/petra.jpg",
  description: "Jordan’s ancient city carved into pink rock, a UNESCO World Heritage Site.",
  lat: 30.3285,
  lng: 35.4444,
},
{
  id: 53,
  name: "Reykjavik",
  image: "/images/reykjavik.jpg",
  description: "Capital of Iceland, gateway to Northern Lights and geothermal wonders.",
  lat: 64.1466,
  lng: -21.9426,
},
{
  id: 54,
  name: "Queenstown",
  image: "/images/queenstown.jpg",
  description: "New Zealand’s adventure capital, surrounded by mountains and lakes.",
  lat: -45.0312,
  lng: 168.6626,
},
{
  id: 55,
  name: "Athens",
  image: "/images/athens.jpg",
  description: "Capital of Greece, home to ancient sites like the Acropolis and Parthenon.",
  lat: 37.9838,
  lng: 23.7275,
},
{
  id: 56,
  name: "Cappadocia",
  image: "/images/cappadocia.jpg",
  description: "Turkey’s region famous for hot air balloon rides over unique rock formations.",
  lat: 38.6431,
  lng: 34.8275,
},
{
  id: 57,
  name: "Buenos Aires",
  image: "/images/buenosaires.jpg",
  description: "Argentina’s capital, known for tango, European-style architecture, and cuisine.",
  lat: -34.6037,
  lng: -58.3816,
},
{
  id: 58,
  name: "Vancouver",
  image: "/images/vancouver.jpg",
  description: "Canadian coastal city known for mountains, ocean views, and vibrant life.",
  lat: 49.2827,
  lng: -123.1207,
},
{
  id: 59,
  name: "Lisbon",
  image: "/images/lisbon.jpg",
  description: "Portugal’s hilly capital with cobbled streets, trams, and colorful neighborhoods.",
  lat: 38.7169,
  lng: -9.1399,
},
{
  id: 60,
  name: "Edinburgh",
  image: "/images/edinburgh.jpg",
  description: "Scotland’s capital with a rich history, castles, and the famous Royal Mile.",
  lat: 55.9533,
  lng: -3.1883,
},
{
  id: 61,
  name: "Cusco",
  image: "/images/cusco.jpg",
  description: "Former Incan capital in Peru, gateway to Machu Picchu.",
  lat: -13.532,
  lng: -71.9675,
},
{
  id: 62,
  name: "Zermatt",
  image: "/images/zermatt.jpg",
  description: "Swiss Alpine resort town beneath the Matterhorn, ideal for skiing and hiking.",
  lat: 46.0207,
  lng: 7.7491,
},
{
  id: 63,
  name: "Fez",
  image: "/images/fez.jpg",
  description: "Moroccan city famous for medieval medina, tanneries, and Islamic architecture.",
  lat: 34.0331,
  lng: -5.0003,
},
{
  id: 64,
  name: "Havana",
  image: "/images/havana.jpg",
  description: "Cuba’s colorful capital with vintage cars and colonial charm.",
  lat: 23.1136,
  lng: -82.3666,
},
{
  id: 65,
  name: "Hobart",
  image: "/images/hobart.jpg",
  description: "Tasmania’s harbor city with rich colonial history and natural beauty.",
  lat: -42.8821,
  lng: 147.3272,
},
{
  id: 66,
  name: "Doha",
  image: "/images/doha.jpg",
  description: "Capital of Qatar, a fast-growing city with futuristic skyline and souqs.",
  lat: 25.276987,
  lng: 51.520008,
},
{
  id: 67,
  name: "Hạ Long Bay",
  image: "/images/halongbay.jpg",
  description: "Vietnam’s bay with emerald waters and towering limestone islands.",
  lat: 20.9101,
  lng: 107.1839,
},
{
  id: 68,
  name: "Seville",
  image: "/images/seville.jpg",
  description: "Spain’s flamenco capital with Moorish architecture and the Alcázar palace.",
  lat: 37.3891,
  lng: -5.9845,
},
{
  id: 69,
  name: "Salar de Uyuni",
  image: "/images/uyuni.jpg",
  description: "Bolivia’s vast salt flat, a surreal mirror during the wet season.",
  lat: -20.1338,
  lng: -67.4891,
},
{
  id: 70,
  name: "Jerusalem",
  image: "/images/jerusalem.jpg",
  description: "Sacred city for Jews, Christians, and Muslims, filled with spiritual sites.",
  lat: 31.7683,
  lng: 35.2137,
},
];

const Destinations = () => {
  const [selected, setSelected] = useState(null);

  return (
    <div className="destination-page">
      <h1>Welcome To The Paradise Tourism</h1>
      <div className="grid">
        {destinations.map((d) => (
          <div className="card" key={d.id} onClick={() => setSelected(d)}>
            <img src={d.image} alt={d.name} />
            <h3>{d.name}</h3>
          </div>
        ))}
      </div>

      {selected && (
        <div className="modal">
          <button className="close" onClick={() => setSelected(null)}>
            X
          </button>
          <h2>{selected.name}</h2>
          <p>{selected.description}</p>
          <MapContainer
            center={[selected.lat, selected.lng]}
            zoom={5}
            style={{ height: "300px", width: "100%", marginTop: "1rem" }}
          >
            <TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />
            <Marker position={[selected.lat, selected.lng]}>
              <Popup>{selected.name}</Popup>
            </Marker>
          </MapContainer>
        </div>
      )}
    </div>
  );
};

export default Destinations;
